# Generated by Django 4.0.3 on 2022-05-18 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_alter_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='address.area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district', to='address.area')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province', to='address.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'tb_address',
                'ordering': ['user'],
            },
        ),
    ]
